import { Footer } from "./Footer";

export function TermsPage() {
    return (
        <>
            <main className="w-full bg-[#ece6e8] px-6 py-16 md:py-24 md:px-12 lg:px-20">
                <div className="max-w-[1200px] mx-auto">
                    <h1 className="font-['Plus_Jakarta_Sans',sans-serif] font-medium text-3xl md:text-4xl lg:text-5xl mb-12">
                        Terms & <span className="font-['Playfair_Display',sans-serif] italic font-normal">Conditions</span>
                    </h1>

                    <div className="font-['Plus_Jakarta_Sans',sans-serif] text-[#1e1e1e] space-y-8 text-base md:text-lg leading-relaxed">
                        <p className="font-bold">Last Updated: February 5, 2026</p>

                        <section>
                            <h2 className="text-xl mb-4 text-black">1. <span className="font-bold">Overview</span></h2>
                            <p>NicheNeeds ("we," "us," "our") is a Creative AI Product Studio. By using our website (nicheneeds.com) and purchasing our products, you agree to these Terms and Conditions.</p>
                        </section>

                        <section>
                            <h2 className="text-xl mb-4 text-black">2. <span className="font-bold">Merchant of Record</span></h2>
                            <p>Our order process is conducted by our online reseller LemonSqueezy.com. Lemon Squeezy is the Merchant of Record for all our orders. They handle payment processing, tax collection, and customer service inquiries related to the transaction.</p>
                        </section>

                        <section>
                            <h2 className="text-xl mb-4 text-black">3. <span className="font-bold">License & Use</span></h2>
                            <p className="mb-4">Upon purchase, you are granted a non-exclusive, non-transferable license to use the software, game, or digital asset for its intended purpose. You may not:</p>
                            <ul className="list-disc pl-6 space-y-2">
                                <li>Decompile, reverse engineer, or attempt to extract the source code of our products.</li>
                                <li>Resell, redistribute, or sub-license the core assets or logic.</li>
                            </ul>
                        </section>

                        <section>
                            <h2 className="text-xl mb-4 text-black">4. <span className="font-bold">AI Disclosure & Disclaimer</span></h2>
                            <p>NicheNeeds products utilize agentic AI development. While we aim for high reliability, products are provided "as-is." We are not responsible for any specific outcomes or outputs generated by AI components.</p>
                        </section>

                        <section>
                            <h2 className="text-xl mb-4 text-black">5. <span className="font-bold">Governing Law</span></h2>
                            <p>These terms are governed by and construed in accordance with the laws of the Netherlands.</p>
                        </section>
                    </div>
                </div>
            </main>
            <Footer />
        </>
    );
}

